### PR TITLE
Add `stRandom` and `stRandom2` testsuites

### PR DESCRIPTION
**Pull request by khaeljy**
Time spent on this PR: 1h

#387 #388

# Pull Request type

Please check the type of change your PR introduces:

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, renaming)
-   [ ] Refactoring (no functional changes, no API changes)
-   [ ] Build-related changes
-   [ ] Documentation content changes
-   [x] Testing

# What is the new behavior?

# Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by khaeljy** [comment]
I don't understand why the tests fail, it works fine on my local workstation (commenting on the `stMemoryStressTest` testsuite, as I don't have enough RAM).

**Comment by Eikix** [comment]
I tried to run the tests in debug mode, but they don't give a reason why the tests are failing.
I'll try to increase the size of the runner and observe the results. 

Let's first merge all PRs in the backlog and then try to do that

**Comment by greged93** [comment]
Any update on this?

**Comment by Eikix** [comment]
> Any update on this?

Trying to increase size of runner

**Comment by greged93** [comment]
Looks like it's missing some skipped tests

**Comment by khaeljy** [comment]
> Looks like it's missing some skipped tests @khaeljy can you maybe take a look at this and update the tests that need to be skipped?

It's strange, maybe it's due to a rebase.
I'll look into it as soon as possible.

**Comment by khaeljy** [comment]
> Looks like it's missing some skipped tests @khaeljy can you maybe take a look at this and update the tests that need to be skipped?

Done!

**Review by Eikix — APPROVED** [review]
lgtm gg

**Pull request merged**
