### PR TITLE
add `stWalletTest` testsuite

### PR DESCRIPTION
**Pull request by TAdev0**
Time spent on this PR: 15min

#427 

# Pull Request type

Please check the type of change your PR introduces:

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, renaming)
-   [ ] Refactoring (no functional changes, no API changes)
-   [ ] Build-related changes
-   [ ] Documentation content changes
-   [x] Testing

# What is the new behavior?

# Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by khaeljy** [comment]
I think you've missed a few errors:

```
 Suite: BlockchainTests/GeneralStateTests/stWalletTest (at /home/runner/work/ef-tests/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stWalletTest)
Ran 42 tests (37 passed, 5 failed, 0 skipped) 

[!] Case /home/runner/work/ef-tests/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stWalletTest/walletConfirm.json failed:
walletConfirm_d0g0v0_Shanghai expected balance 0x0000000000000000000000000000000000000000000000000000000000000009, got 0x0
[!] Case /home/runner/work/ef-tests/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stWalletTest/walletExecuteOverDailyLimitMultiOwner.json failed:
walletExecuteOverDailyLimitMultiOwner_d0g0v0_Shanghai expected storage value 0x00000000000000000000000000000000296cd3823267fa5bebc02e090063c36d for 0xec0e71ad0a90ffe1909d27dac207f7680abba42d, got 0x0000000000000000000000000000000049c83d7507e4746010425e1dfbfb88ca
[!] Case /home/runner/work/ef-tests/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stWalletTest/walletExecuteOverDailyLimitOnlyOneOwner.json failed:
walletExecuteOverDailyLimitOnlyOneOwner_d0g0v0_Shanghai expected storage value 0x00000000000000000000000000000000fce5edbc8e2a8697c15331677e6ebaaa for 0xec0e71ad0a90ffe1909d27dac207f7680abba42d, got 0x0000000000000000000000000000000000000000000000000000000000000000
[!] Case /home/runner/work/ef-tests/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stWalletTest/walletExecuteOverDailyLimitOnlyOneOwnerNew.json failed:
walletExecuteOverDailyLimitOnlyOneOwnerNew_d0g0v0_Shanghai expected storage value 0x00000000000000000000000000000000fce5edbc8e2a8697c15331677e6ebaaa for 0xec0e71ad0a90ffe1909d27dac207f7680abba42d, got 0x0000000000000000000000000000000000000000000000000000000000000000
[!] Case /home/runner/work/ef-tests/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stWalletTest/walletExecuteUnderDailyLimit.json failed:
walletExecuteUnderDailyLimit_d0g0v0_Shanghai expected storage value 0x0000000000000000000000000000000000000000000000000000000000000001 for 0xec0e71ad0a90ffe1909d27dac207f7680abba42d, got 0x0000000000000000000000000000000000000000000000000000000000000000
test blockchain_tests::st_wallet_test ... FAILED
```

**Comment by TAdev0** [comment]
now everything should be good :) thank you @khaeljy

**Review by khaeljy — COMMENTED** [review]
Lgtm 👍

**Comment by TAdev0** [comment]
@danilowhk  ready to be merged

**Review by danilowhk — APPROVED** [review]

**Pull request merged**
