### PR TITLE
Readme jq

### PR DESCRIPTION
**Pull request by Gerson2102**
# Pull Request type

Adding jq for the requirements to contribute.

Time spent on this PR: 1 minute

Resolves: #706 

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [X] Documentation content changes
- [ ] Testing

### CODE REVIEW

**Comment by Gerson2102** [comment]
I dont know if it was a good idea have done a git rebase of my branch form main and then do some changes to the readme and open this PR.

**Review by enitrat — DISMISSED** [review]

**Comment by enitrat** [comment]
linter does not pass, can you check?

**Comment by Gerson2102** [comment]
I'm trying to run locally `trunk fmt` but it does not appear the readme. Which is the file that is not formated according to the error. So i cant add the file to commit it. I dont know why it does not appear.

**Comment by Gerson2102** [comment]
image
These files changed because i did an upgrade, but i dont know if its correct to add those changes for the project.

**Comment by enitrat** [comment]
trunk is just an aggregator of linter that runs prettier under the hood I think. Here the issue would be that the line is too long

**Review by enitrat — APPROVED** [review]

**Review by greged93 — APPROVED** [review]

**Pull request merged**
